nameOverride: ""
fullnameOverride: ""

labels: { }
annotations: { }
deploymentLabels: { }
deploymentAnnotations: { }
podLabels: { }
podAnnotations: { }

containerName: "tcp-echo"

image:
  registry: "docker.io"
  repository: "abrarov/tcp-echo"
  tag: "latest"
  pullPolicy: "IfNotPresent"

livenessProbe:
  initialDelay: 2

readinessProbe:
  initialDelay: 2

replicaCount: 1

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000140001

service:
  labels: { }
  annotations: { }
  port: 9007
  nodePort: 30007

tcpEcho:
  port: 9007
  listenBacklog: 6
  inactivityTimeout: 60
  stopTimeout: 120
  maxSessions: 10000
  bufferSize: 4096

test:
  podLabels: { }
  podAnnotations: { }
  containerName: "tcp-echo-test"
  image:
    registry: "docker.io"
    repository: "busybox"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  message: "Hello World!"
