{{- if .Values.image.pullSecret -}}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "tcp-echo.imagePullSecretName" . | quote }}
  labels:
    {{- include "tcp-echo.labels" . | nindent 4 }}
    {{- include "tcp-echo.componentLabels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "tcp-echo.tplValuesRender" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- include "tcp-echo.tplValuesRender" (dict "value" .Values.annotations "context" $) | nindent 4 }}
  {{- end }}
type: "kubernetes.io/dockerconfigjson"
data:
  .dockerconfigjson: {{ include "tcp-echo.dockerRegistryAuthenticationConfig" (dict "imageRegistry" .Values.image.registry "credentials" .Values.image.pullSecret) | quote }}
{{- end }}
